[package]
name = "op1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustysynth = "1.3.1"
tinyaudio="0.1.2"
itertools="0.11.0"